source "https://rubygems.org"

gem "friendly_id"
gem "social-share-button"
gem "chosen-rails"
gem "exception_notification"
gem "globalize"
gem "omniauth-facebook"
gem "omniauth-twitter"
gem "omniauth-google-oauth2"
gem "omniauth-github"
gem "client_side_validations", github: "DavyJonesLocker/client_side_validations", branch: "4-2-stable"
gem "ancestry"
gem "sublimevideo_rails"
gem "devise"
gem "ckeditor"
gem "pygments.rb"
gem "redcarpet"
gem "mini_magick"
gem "carrierwave"
gem "font-awesome-rails"
gem "bootstrap-sass"
gem "will_paginate"
gem "bootstrap-will_paginate"
gem "rails", "4.2.1"
gem "mysql2"
gem "sass-rails"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.1.0"
gem "jquery-rails"
gem "turbolinks"
gem "jbuilder", "~> 2.0"
gem "sdoc", "~> 0.4.0", group: :doc
group :development, :test do
  gem "byebug"  
  gem "web-console", "~> 2.0"
  gem "spring"
  gem "faker"
  gem "letter_opener"
end

